
package com.dao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustDao", targetNamespace = "http://dao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.dao.AddressClass>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddress", targetNamespace = "http://dao.com/", className = "com.dao.GetAddress")
    @ResponseWrapper(localName = "getAddressResponse", targetNamespace = "http://dao.com/", className = "com.dao.GetAddressResponse")
    @Action(input = "http://dao.com/CustDao/getAddressRequest", output = "http://dao.com/CustDao/getAddressResponse")
    public List<AddressClass> getAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPMethod", targetNamespace = "http://dao.com/", className = "com.dao.GetPMethod")
    @ResponseWrapper(localName = "getPMethodResponse", targetNamespace = "http://dao.com/", className = "com.dao.GetPMethodResponse")
    @Action(input = "http://dao.com/CustDao/getPMethodRequest", output = "http://dao.com/CustDao/getPMethodResponse")
    public String getPMethod(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setPMethod", targetNamespace = "http://dao.com/", className = "com.dao.SetPMethod")
    @ResponseWrapper(localName = "setPMethodResponse", targetNamespace = "http://dao.com/", className = "com.dao.SetPMethodResponse")
    @Action(input = "http://dao.com/CustDao/setPMethodRequest", output = "http://dao.com/CustDao/setPMethodResponse")
    public int setPMethod(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertXml", targetNamespace = "http://dao.com/", className = "com.dao.InsertXml")
    @ResponseWrapper(localName = "insertXmlResponse", targetNamespace = "http://dao.com/", className = "com.dao.InsertXmlResponse")
    @Action(input = "http://dao.com/CustDao/insertXmlRequest", output = "http://dao.com/CustDao/insertXmlResponse")
    public int insertXml(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.dao.ProductClass>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSProducts", targetNamespace = "http://dao.com/", className = "com.dao.GetSProducts")
    @ResponseWrapper(localName = "getSProductsResponse", targetNamespace = "http://dao.com/", className = "com.dao.GetSProductsResponse")
    @Action(input = "http://dao.com/CustDao/getSProductsRequest", output = "http://dao.com/CustDao/getSProductsResponse")
    public List<ProductClass> getSProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setAddressMethod", targetNamespace = "http://dao.com/", className = "com.dao.SetAddressMethod")
    @ResponseWrapper(localName = "setAddressMethodResponse", targetNamespace = "http://dao.com/", className = "com.dao.SetAddressMethodResponse")
    @Action(input = "http://dao.com/CustDao/setAddressMethodRequest", output = "http://dao.com/CustDao/setAddressMethodResponse")
    public int setAddressMethod(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        AddressClass arg1);

}
