
package com.dao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerDao", targetNamespace = "http://dao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerDao {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws ParseException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "newInstall", targetNamespace = "http://dao.com/", className = "com.dao.NewInstall")
    @ResponseWrapper(localName = "newInstallResponse", targetNamespace = "http://dao.com/", className = "com.dao.NewInstallResponse")
    @Action(input = "http://dao.com/CustomerDao/newInstallRequest", output = "http://dao.com/CustomerDao/newInstallResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://dao.com/CustomerDao/newInstall/Fault/ParseException")
    })
    public void newInstall(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws ParseException_Exception
    ;

}
